name: Wayback Machine Crawl
on: workflow_dispatch
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build-list:
    name: Build Url List
    environment: crawl-delay
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.urls.outputs.urls }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout Sitemap File
        with:
          ref: gh-pages
          sparse-checkout: |
            sitemap.txt
          sparse-checkout-cone-mode: false
      - id: urls
        shell: pwsh
        run: |
          [string[]] $urls = @();
          [string[]] $domains = @("https://blog.halomak.es", "https://blog.haley.contact", "https://blog.alexgriffith.me")
          Get-Content "sitemap.txt" | ForEach-Object {
            [string] $path = $_;
            $domains | ForEach-Object {
              [string] $domain = $_;
              $url = "$($domain)$($path)"
              $urls += $url;
              # Write-Host "Warming up $url";
              # Invoke-WebRequest $url -AllowInsecureRedirect -ErrorAction Ignore -ProgressAction SilentlyContinue | Out-Null;
            }
          }
          [string] $asJson = $urls | ConvertTo-Json -Compress;
          "urls=$asJson" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: List URLs
        run: |
          echo "${{ steps.urls.outputs.urls }}"
  crawl-site:
    name: Crawl Site
    runs-on: ubuntu-latest
    needs: build-list
    continue-on-error: true
    strategy:
      max-parallel: 2
      matrix:
        url: ${{ fromJSON(needs.build-list.outputs.urls) }}
    steps:
      - name: Archive Site
        uses: JamieMagee/wayback@v2
        with:
          url: ${{ matrix.url }}
          saveOutlinks: true
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '5'