name: Wayback Machine Crawl
on:
  workflow_dispatch:
    inputs:      
      attemptNumber:
        description: 'Attempt number'
        required: false
        default: '1'
      maxAttempts:
        description: 'Max attempts'
        required: false
        default: '5'
jobs:
  publish:
    environment: crawl-delay
    runs-on: ubuntu-latest
    steps:
      - name: Archive Site
        uses: JamieMagee/wayback@v2
